const data = {
  products: {
    fleeceSherpas: [
      {
        name: "Fleece Sherpa Jacket",
        category: "Winter Apparel",
        color: "Black",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-sherpa/black-sherpa-big.png",
          "/images/jacket-sherpa/black-sherpa-small.png",
          "/images/jacket-sherpa/black-sherpa.png",
        ],
        description: [
          "Premium human grade teddy sherpa exterior",
          "Soft polar fleece interior",
          "Double breasted front buttons for perfect fit",
          "Dual buttons at the back of the neck to stabilize oversized hood",
          "Hole opening back of the neck for leash",
          "Ribbed knit bottom hem & sleeve cuffs",
          "Adjustable drawstring",
          "Perfect for indoor and outdoor wear",
          "Machine wash cold, tumble dry cold, avoid softener",
        ],
      },
      {
        name: "Fleece Sherpa Jacket",
        category: "Winter Apparel",
        color: "Green",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-sherpa/green-sherpa-big.png",
          "/images/jacket-sherpa/green-sherpa-small.png",
          "/images/jacket-sherpa/green-sherpa.png",
        ],
        description: [
          "Premium human grade teddy sherpa exterior",
          "Soft polar fleece interior",
          "Double breasted front buttons for perfect fit",
          "Dual buttons at the back of the neck to stabilize oversized hood",
          "Hole opening back of the neck for leash",
          "Ribbed knit bottom hem & sleeve cuffs",
          "Adjustable drawstring",
          "Perfect for indoor and outdoor wear",
          "Machine wash cold, tumble dry cold, avoid softener",
        ],
      },
      {
        name: "Fleece Sherpa Jacket",
        category: "Winter Apparel",
        color: "Grey",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-sherpa/grey-sherpa-big.png",
          "/images/jacket-sherpa/grey-sherpa-small.png",
          "/images/jacket-sherpa/grey-sherpa.png",
        ],
        description: [
          "Premium human grade teddy sherpa exterior",
          "Soft polar fleece interior",
          "Double breasted front buttons for perfect fit",
          "Dual buttons at the back of the neck to stabilize oversized hood",
          "Hole opening back of the neck for leash",
          "Ribbed knit bottom hem & sleeve cuffs",
          "Adjustable drawstring",
          "Perfect for indoor and outdoor wear",
          "Machine wash cold, tumble dry cold, avoid softener",
        ],
      },
      {
        name: "Fleece Sherpa Jacket",
        category: "Winter Apparel",
        color: "Maroon",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-sherpa/maroon-sherpa-big.png",
          "/images/jacket-sherpa/maroon-sherpa-small.png",
          "/images/jacket-sherpa/maroon-sherpa.png",
        ],
        description: [
          "Premium human grade teddy sherpa exterior",
          "Soft polar fleece interior",
          "Double breasted front buttons for perfect fit",
          "Dual buttons at the back of the neck to stabilize oversized hood",
          "Hole opening back of the neck for leash",
          "Ribbed knit bottom hem & sleeve cuffs",
          "Adjustable drawstring",
          "Perfect for indoor and outdoor wear",
          "Machine wash cold, tumble dry cold, avoid softener",
        ],
      },
      {
        name: "Fleece Sherpa Jacket",
        category: "Winter Apparel",
        color: "Orange",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-sherpa/orange-sherpa-big.png",
          "/images/jacket-sherpa/orange-sherpa-small.png",
          "/images/jacket-sherpa/orange-sherpa.png",
        ],
        description: [
          "Premium human grade teddy sherpa exterior",
          "Soft polar fleece interior",
          "Double breasted front buttons for perfect fit",
          "Dual buttons at the back of the neck to stabilize oversized hood",
          "Hole opening back of the neck for leash",
          "Ribbed knit bottom hem & sleeve cuffs",
          "Adjustable drawstring",
          "Perfect for indoor and outdoor wear",
          "Machine wash cold, tumble dry cold, avoid softener",
        ],
      },
    ],

    jacketVests: [
      {
        name: "Parka Jacket Vest",
        category: "Winter Apparel",
        color: "Black",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-vest/black-vest-big.png",
          "/images/jacket-vest/black-vest-small.png",
          "/images/jacket-vest/black-vest.png",
        ],
        description: [
          "This sleek tech-wear inspired parka will keep your dog dry and warm on the coldest winter days",
          "Keep Dry: Water-resistant exterior shell with reflective strips on the side",
          "Perfect Fit: Double breasted front buttons for perfect fit",
          "Extra Warmth: Cotton insulation and polar fleece interior",
          "Zipper hole opening for leash attachment",
          "Pocket for poop bags and treats ",
          "Material: Shell 100% Polyester, Filling 100% Cotton, Lining 100% Polyester",
          "Care: Machine wash cold, hang dry, do not iron  ",
        ],
      },
      {
        name: "Parka Jacket Vest",
        category: "Winter Apparel",
        color: "Olive",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-vest/olive-vest-big.png",
          "/images/jacket-vest/olive-vest-small.png",
          "/images/jacket-vest/olive-vest.png",
        ],
        description: [
          "This sleek tech-wear inspired parka will keep your dog dry and warm on the coldest winter days",
          "Keep Dry: Water-resistant exterior shell with reflective strips on the side",
          "Perfect Fit: Double breasted front buttons for perfect fit",
          "Extra Warmth: Cotton insulation and polar fleece interior",
          "Zipper hole opening for leash attachment",
          "Pocket for poop bags and treats ",
          "Material: Shell 100% Polyester, Filling 100% Cotton, Lining 100% Polyester",
          "Care: Machine wash cold, hang dry, do not iron  ",
        ],
      },
      {
        name: "Parka Jacket Vest",
        category: "Winter Apparel",
        color: "Red",
        countInStock: 10,
        price: 25,
        rating: 4.5,
        reviews: 120,
        images: [
          "/images/jacket-vest/red-vest-big.png",
          "/images/jacket-vest/red-vest-small.png",
          "/images/jacket-vest/red-vest.png",
        ],
        description: [
          "This sleek tech-wear inspired parka will keep your dog dry and warm on the coldest winter days",
          "Keep Dry: Water-resistant exterior shell with reflective strips on the side",
          "Perfect Fit: Double breasted front buttons for perfect fit",
          "Extra Warmth: Cotton insulation and polar fleece interior",
          "Zipper hole opening for leash attachment",
          "Pocket for poop bags and treats ",
          "Material: Shell 100% Polyester, Filling 100% Cotton, Lining 100% Polyester",
          "Care: Machine wash cold, hang dry, do not iron  ",
        ],
      },
    ],
  },
};

export default data;
